[[attribute]]
type = "Nominal"
values = ["f","t"]

[[attribute]]
type = "Nominal"
values = ["f","t"]

[[attribute]]
type = "Nominal"
values = ["f","t"]

[[attribute]]
type = "Nominal"
values = ["f","t"]

[[attribute]]
type = "Nominal"
values = ["f","t"]

[[attribute]]
type = "Nominal"
values = ["t","f"]

[[attribute]]
type = "Nominal"
values = ["f","t"]

[[attribute]]
type = "Nominal"
values = ["f","t"]

[[attribute]]
type = "Nominal"
values = ["f","t"]

[[attribute]]
type = "Nominal"
values = ["f","t"]

[[attribute]]
type = "Nominal"
values = ["f","t"]

[[attribute]]
type = "Nominal"
values = ["f","t"]

[[attribute]]
type = "Nominal"
values = ["g","l"]

[[attribute]]
type = "Nominal"
values = ["f","t"]

[[attribute]]
type = "Nominal"
values = ["n","b","w"]

[[attribute]]
type = "Nominal"
values = ["f","t"]

[[attribute]]
type = "Nominal"
values = ["f","t"]

[[attribute]]
type = "Nominal"
values = ["t","f"]

[[attribute]]
type = "Nominal"
values = ["f","t"]

[[attribute]]
type = "Nominal"
values = ["f","t"]

[[attribute]]
type = "Nominal"
values = ["t","f"]

[[attribute]]
type = "Nominal"
values = ["f","t"]

[[attribute]]
type = "Nominal"
values = ["f","t"]

[[attribute]]
type = "Nominal"
values = ["f","t"]

[[attribute]]
type = "Nominal"
values = ["f","t"]

[[attribute]]
type = "Nominal"
values = ["f","t"]

[[attribute]]
type = "Nominal"
values = ["f","t"]

[[attribute]]
type = "Nominal"
values = ["f","t"]

[[attribute]]
type = "Nominal"
values = ["f","t"]

[[attribute]]
type = "Nominal"
values = ["f","t"]

[[attribute]]
type = "Nominal"
values = ["t","f"]

[[attribute]]
type = "Nominal"
values = ["f","t"]

[[attribute]]
type = "Nominal"
values = ["f","t"]

[[attribute]]
type = "Nominal"
values = ["t","f"]

[[attribute]]
type = "Nominal"
values = ["f","t"]

[[attribute]]
type = "Nominal"
values = ["f","t"]

[[attribute]]
type = "Nominal"
values = ["f","t"]

[[attribute]]
type = "Nominal"
values = ["f","t"]

[[attribute]]
type = "Nominal"
values = ["f","t"]

[[attribute]]
type = "Nominal"
values = ["f","t"]

[[attribute]]
type = "Nominal"
values = ["f","t"]

[[attribute]]
type = "Nominal"
values = ["f","t"]



[[attribute]]
type = "Nominal"
values = ["f","t"]

[[attribute]]
type = "Nominal"
values = ["t","f"]

[[attribute]]
type = "Nominal"
values = ["f","t"]

[[attribute]]
type = "Nominal"
values = ["f","t"]

[[attribute]]
type = "Nominal"
values = ["f","t"]

[[attribute]]
type = "Nominal"
values = ["f","t"]

[[attribute]]
type = "Nominal"
values = ["f","t"]

[[attribute]]
type = "Nominal"
values = ["f","t"]

[[attribute]]
type = "Nominal"
values = ["f","t"]

[[attribute]]
type = "Nominal"
values = ["f","t"]

[[attribute]]
type = "Nominal"
values = ["f","t"]

[[attribute]]
type = "Nominal"
values = ["t","f"]

[[attribute]]
type = "Nominal"
values = ["f","t"]

[[attribute]]
type = "Nominal"
values = ["f","t"]

[[attribute]]
type = "Nominal"
values = ["t","f"]

[[attribute]]
type = "Nominal"
values = ["f","t"]

[[attribute]]
type = "Nominal"
values = ["f","t"]

[[attribute]]
type = "Nominal"
values = ["f","t"]

[[attribute]]
type = "Nominal"
values = ["f","t"]

[[attribute]]
type = "Nominal"
values = ["f","t"]

[[attribute]]
type = "Nominal"
values = ["f","t"]

[[attribute]]
type = "Nominal"
values = ["f","t"]

[[attribute]]
type = "Nominal"
values = ["f","t"]