[general]
normalise_data = true

# Nominal data only

[[file_names]]
name = "Chess"
file_name = "./data/chess_shuffled_test.csv"
file_stats = "./data/chess_shuffled_test.csv.toml"
has_header = false
class_index = "last"


